In [17]:
#Importing necessary Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle
from sklearn.impute import SimpleImputer

In [25]:
#Importing the dataset
ds = pd.read_csv('diabetes.csv')
ds.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [26]:
ds['Glucose'] = ds['Glucose'].replace(0,'NaN')
ds['BloodPressure'] = ds['BloodPressure'].replace(0,'NaN')
ds['SkinThickness'] = ds['SkinThickness'].replace(0,'NaN')
ds['Insulin'] = ds['Insulin'].replace(0,'NaN')
ds['BMI'] = ds['BMI'].replace(0,'NaN')
ds['DiabetesPedigreeFunction'] = ds['DiabetesPedigreeFunction'].replace(0,'NaN')
ds['Age'] = ds['Age'].replace(0,'NaN')
ds.head()

Pregnancies Glucose BloodPressure SkinThickness Insulin   BMI  \
0            6     148            72            35     NaN  33.6   
1            1      85            66            29     NaN  26.6   
2            8     183            64           NaN     NaN  23.3   
3            1      89            66            23      94  28.1   
4            0     137            40            35     168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [27]:
ds.shape

(768, 9)

In [29]:
#print(ds.iloc[[:,74:80]])
print(ds[72:80])

    Pregnancies Glucose BloodPressure SkinThickness Insulin   BMI  \
72           13     126            90           NaN     NaN  43.4   
73            4     129            86            20     270  35.1   
74            1      79            75            30     NaN  32.0   
75            1     NaN            48            20     NaN  24.7   
76            7      62            78           NaN     NaN  32.6   
77            5      95            72            33     NaN  37.7   
78            0     131           NaN           NaN     NaN  43.2   
79            2     112            66            22     NaN  25.0   

    DiabetesPedigreeFunction  Age  Outcome  
72                     0.583   42        1  
73                     0.231   23        0  
74                     0.396   22        0  
75                     0.140   22        0  
76                     0.391   41        0  
77                     0.370   27        0  
78                     0.270   26        1  
79                

In [30]:
#Allocating X and Y
X = ds.iloc[:, 0:8].values
Y = ds.iloc[:, -1].values
print(X[3])
print(Y[3])

[1 89 66 23 94 28.1 0.167 21]
0


In [33]:
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(X[:, 0:8])
X[:, 0:8] = imputer.transform(X[:, 0:8])

In [35]:
print(X[78])

[0.0 131.0 72.40518417462484 29.153419593345657 155.5482233502538 43.2
 0.27 26.0]


In [36]:
#Splitting Test and Train Data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [37]:
#Standardize features by removing the mean and scaling to unit variance
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [38]:
print(X_train[3])
print(X_test[3])

[-0.8354355  -0.41961392 -1.38693491 -0.93541649 -0.24822304 -1.06309633
  1.10091422 -0.88240283]
[ 0.32707418  1.46539761 -0.05383821 -1.1617631   0.21107601 -0.97724247
  0.36202408  1.44969086]


In [39]:
#Training the model 
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0) #Since output needs to be binary
classifier.fit(X_train, Y_train)

SVC(kernel='sigmoid', random_state=0)

In [40]:
#Predicting with X_test
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]

In [41]:
#Checking Accuracy
print("Accuracy: {}".format(classifier.score(X_test,y_pred)))

Accuracy: 1.0


In [42]:
#Test new inputs here 
print(classifier.predict(sc.transform([[6,148,72,35,0,33.6,0.627,50]]))) 

[1]


In [43]:
x = np.array([[5,140,72,34,0,33.8,0.627,45]])
x 

array([[  5.   , 140.   ,  72.   ,  34.   ,   0.   ,  33.8  ,   0.627,
         45.   ]])

In [44]:
x = sc.transform(x)
x = x.astype(float)
x

array([[ 0.32707418,  0.60556779, -0.05383821,  0.53583644, -1.79835731,
         0.16747569,  0.48216882,  0.9499565 ]])

In [45]:
y_pred = classifier.predict(x)
y_pred

array([1])

In [46]:
data = {"model" : classifier,"transform" : sc} #Dictionary
with open('diabetes_model_svm.pkl', 'wb') as file:
  pickle.dump(data,file)

In [47]:
classifier_loaded = data["model"]
sc = data["transform"]

with open('diabetes_model_svm.pkl', 'rb') as file:
  pickle.load(file)


In [48]:
y_pred = classifier_loaded.predict(x)
y_pred

array([1])