In [18]:
#Importing necessary Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [2]:
#Importing the dataset
ds = pd.read_csv('diabetes.csv')
ds.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
#Allocating X and Y
X = ds.iloc[:, 0:8].values
Y = ds.iloc[:, -1].values
print(X[3])
print(Y[3])

[ 1.    89.    66.    23.    94.    28.1    0.167 21.   ]
0


In [5]:
#Splitting Test and Train Data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [6]:
#Standardize features by removing the mean and scaling to unit variance
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(X_train[3])
print(X_test[3])

[-0.8354355  -0.37427121 -0.67706208  0.02345601  0.45029859 -0.88604319
  1.10091422 -0.88240283]
[ 0.32707418  1.4190946   0.14198211 -0.10123654  0.79102609 -0.81016901
  0.36202408  1.44969086]


In [8]:
#Training the model 
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0) #Since output needs to be binary
classifier.fit(X_train, Y_train)

SVC(kernel='sigmoid', random_state=0)

In [ ]:
#Predicting with X_test
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

In [10]:
#Checking Accuracy
print("Accuracy: {}".format(classifier.score(X_test,y_pred)))

Accuracy: 1.0


In [11]:
#Test new inputs here 
print(classifier.predict(sc.transform([[6,148,72,35,0,33.6,0.627,50]]))) 

[1]


In [12]:
x = np.array([[5,140,72,34,0,33.8,0.627,45]])
x 

array([[  5.   , 140.   ,  72.   ,  34.   ,   0.   ,  33.8  ,   0.627,
         45.   ]])

In [15]:
x = sc.transform(x)
x = x.astype(float)
x

array([[-1.42570159, -3.92276889, -3.72474849, -1.3627399 , -0.70566731,
        -4.58456545, -1.25947575, -3.02450837]])

In [16]:
y_pred = classifier.predict(x)
y_pred

array([1])

In [19]:
data = {"model" : classifier} #Dictionary
with open('diabetes_model_svm.pkl', 'wb') as file:
  pickle.dump(data,file)

In [20]:
classifier_loaded = data["model"]

with open('diabetes_model_svm.pkl', 'rb') as file:
  pickle.load(file)


In [21]:
y_pred = classifier_loaded.predict(x)
y_pred

array([1])